version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                # location of requirements.txt
    schedule:
      interval: "weekly"          # daily, weekly, or monthly
    allow:
      - dependency-type: "direct" # only updates explicitly listed packages
